services:
  # Backend Express server
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/dungeon-lab
      - JWT_SECRET=your_jwt_secret_here
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=dungeon-lab
      - CORS_ORIGIN=http://localhost:8080
    depends_on:
      - mongo
      - minio
    restart: unless-stopped

  # Frontend Vue.js app
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Important: In the browser environment, use the host machine URL
      # not the Docker internal service name
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server
    restart: unless-stopped

  # MongoDB database
  mongo:
    image: mongo:latest
    profiles: ["db"]
    ports:
      - "27017:27017"
    restart: unless-stopped

  # MinIO object storage
  minio:
    image: minio/minio:latest
    profiles: ["db"]
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # Service to create the bucket and set policies
  createbuckets:
    image: minio/mc
    profiles: ["db"]
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/dungeon-lab --ignore-existing;
      /usr/bin/mc anonymous set download myminio/dungeon-lab;
      exit 0;
      " 